# ---
# Docker Compose containers for use in Astro.js projects.
# @see https://docs.docker.com/compose/
# ---

version: '3.8'

services:

  node:
    image: node
    container_name: node_astro-blog
    ports:
      - 4321:4321
      - 80:80
    networks:
      - network
    volumes:
      - ./:/home/node
    working_dir: /home/node/
    restart: unless-stopped
    tty: true

networks:
  network:
    driver: bridge
